language: python
python:
  - '3.8'
  - '3.9'

install:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="_Projet8.settings"

branches:
  only:
    - travisci

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test

services:
  - postgresql
