language: python
python:
  - '3.9'

install:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="_Projet8.settings"

branches:
  only:
    - master

script:
  - python manage.py test

services:
  - postgresql
