# Generated by Django 3.1.7 on 2021-03-05 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210303_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=155, unique=True),
            preserve_default=False,
        ),
    ]
