# Generated by Django 3.1.7 on 2021-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20210305_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
