# Generated by Django 3.1.7 on 2021-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20210308_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.CharField(max_length=155, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal',
            field=models.CharField(max_length=155, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.CharField(max_length=155, null=True, unique=True),
        ),
    ]
